Repository wecode-bootcamp-korea/32-1st-boyFriends-frontend, pull requests merged in 2022-05, with the labels that each got.

#9 [32기 서성용] 공통사항 수정
  public/data/hi.md
  public/data/navMock/navMock.json
  public/data/productListMock/productListMock.json
  pull_request_template.md
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/User/SignIn/SignIn.js
  src/pages/User/SignIn/SignIn.scss
  src/pages/User/SignUp/SignUp.js
  src/pages/User/SignUp/SignUp.scss
Labels: Status: Accepted

#10 [32기 안훈기] nav바 추가기능 구현중
  public/data/navMock/navMock.json
  src/Router.js
  src/components/Nav/Menulist.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: 추가 기능 구현중

#4 [32기 서성용] Main page 기능 및 UI 구현중
  .vscode/launch.json
  public/data/mainMock/mainMock.json
  public/data/productListMock/ProductListMock.json
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/Header/Header.js
  src/pages/Main/components/Header/Header.scss
  src/pages/Main/components/Section/Section.js
  src/pages/Main/components/Section/Section.scss
  src/pages/Main/components/Section/SectionCard.js
  src/pages/Main/components/Section/SectionCard.scss
  src/pages/Main/components/Section/SectionMiniCard.js
  src/pages/Main/components/common/CircleBtn.js
  src/pages/Main/components/common/Common.js
  src/pages/Main/components/common/DirectionBtn.js
  src/pages/Main/components/common/ImageCard.js
Labels: Status: 추가 기능 구현중

#6 [32기 안훈기] 로그인 페이지 필수기능 구현 완료
  src/pages/User/SignIn/SignIn.js
  src/pages/User/SignIn/SignIn.scss
Labels: Status: 수정 요청

#7 [32기 황석영] Product Detail state 관리 및 기능 구현 중
  public/data/ReviewData.json
  src/Router.js
  src/components/Nav/Menulist.scss
  src/components/Nav/Nav.js
  src/pages/Product/ProductDetail/ProductDetail.js
  src/pages/Product/ProductDetail/ProductDetail.scss
  src/pages/Product/ProductDetail/ProductInfoWrapper/ProductImgList/ProductImgList.js
  src/pages/Product/ProductDetail/ProductInfoWrapper/ProductImgList/ProductImgList.scss
  src/pages/Product/ProductDetail/ProductInfoWrapper/ProductInfoWrapper.js
  src/pages/Product/ProductDetail/ProductInfoWrapper/ProductInfoWrapper.scss
  src/pages/Product/ProductDetail/ProductPurchase/PointAccumulate/PointAccumulate.js
  src/pages/Product/ProductDetail/ProductPurchase/PointAccumulate/PointAccumulate.scss
  src/pages/Product/ProductDetail/ProductPurchase/ProductOptionSelect/ProductOptionSelect.js
  src/pages/Product/ProductDetail/ProductPurchase/ProductOptionSelect/ProductOptionSelect.scss
  src/pages/Product/ProductDetail/ProductPurchase/ProductOptionSelect/ResultPrice/ResultPrice.js
  src/pages/Product/ProductDetail/ProductPurchase/ProductOptionSelect/ResultPrice/ResultPrice.scss
  src/pages/Product/ProductDetail/ProductPurchase/ProductOptionSelect/SelectedProduct/SelectedProduct.js
  src/pages/Product/ProductDetail/ProductPurchase/ProductPurchase.js
  src/pages/Product/ProductDetail/ProductPurchase/ProductPurchase.scss
  src/pages/Product/ProductDetail/ProductPurchase/ProductTitle/ProductTitle.js
  src/pages/Product/ProductDetail/ProductPurchase/ProductTitle/ProductTitle.scss
  src/pages/Product/ProductDetail/ProductPurchase/PurchaseButton/PurchaseButton.js
  src/pages/Product/ProductDetail/ProductPurchase/PurchaseButton/PutchaseButton.scss
  src/pages/Product/ProductDetail/ProductReview/Review.js
  src/pages/Product/ProductDetail/ProductReview/Review.scss
  src/pages/Product/ProductDetail/ProductReview/ReviewComment/ReviewComment.js
  src/pages/Product/ProductDetail/ProductReview/ReviewComment/ReviewComment.scss
  src/pages/Product/ProductDetail/ProductReview/ReviewMap/ReviewMap.js
  src/pages/Product/ProductDetail/ProductReview/ReviewMap/ReviewMap.scss
  src/pages/Product/ProductList/Product/Product.js
  src/pages/Product/ProductList/Product/ProductInfo/ProductInfo.js
  src/pages/Product/ProductList/Product/ProductInfo/ProductInfo.scss
  src/pages/Product/ProductList/Product/ProductStatus/ProductStatus.scss
  src/pages/Product/ProductList/ProductList.js
  src/pages/Product/ProductList/ProductNavTab/ProductNavTab.js
Labels: Status: 추가 기능 구현중

#5 [32기 안훈기] 회원가입 페이지 필수기능 구현완료
  public/data/SignUpMock/contentsData.json
  src/pages/User/SignUp/Contents.js
  src/pages/User/SignUp/Contents.scss
  src/pages/User/SignUp/SignUp.js
  src/pages/User/SignUp/SignUp.scss
Labels: Status: 도움 요청, Status: 리뷰 요청

#2 [32기 전형준] Cart페이지, 리뷰댓글 기능 완성
  cart.zip
  public/data/cartData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartEmpty/CartEmpty.js
  src/pages/Cart/CartEmpty/CartEmpty.scss
  src/pages/Cart/CartInfoBox/CartInProduct.js
  src/pages/Cart/CartInfoBox/CartInProduct.scss
  src/pages/Cart/CartInfoBox/CartInfo.js
  src/pages/Cart/CartInfoBox/CartInfo.scss
Labels: Status: 추가 기능 구현중
